apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: awesome-app
spec:
  selector:
    matchLabels:
      app: awesome-app
  template:
    metadata:
      labels:
        app: awesome-app
    spec:
      containers:
        - name: awesome-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - mountPath: /board/
              name: awesome-app-volume
      volumes:
        - name: awesome-app-volume
          hostPath:
            path: /opt/
