apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awesome-app
  template:
    metadata:
      labels:
        app: awesome-app
    spec:
      containers:
        - name: awesome-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /board/
              name: awesome-app-volume
      volumes:
        - name: awesome-app-volume
          hostPath:
            path: /opt/
