apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awesome-front
  template:
    metadata:
      labels:
        app: awesome-front
    spec:
      containers:
        - name: awesome-front
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: awesome-front-volume
      volumes:
        - name: awesome-front-volume
          hostPath:
            path: /opt/
