apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:11
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.databasePassword }}
            - name: POSTGRES_DB
              value: {{ .Values.databaseName }}
            - name: POSTGRES_USER
              value: {{ .Values.databaseUser }}
          ports:
            - containerPort: 5432



      
        
